FROM php:7.4-apache

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install php7.4-mysqli php7.4-mysql php7.4-pgsql php7.4-redis php7.4-bz2 php7.4-dba php7.4-gd php7.4-imagick php7.4-intl php7.4-mcrypt php7.4-soap \
    && apt-get install -y locales locales-all \
    && apt-get install -y make \
    && apt-get install -y build-essential \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
RUN rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Budapest /etc/localtime
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Install NodeJS
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update && apt-get install -y nodejs && apt-get clean

# Install Composer
COPY --from=composer:1.10 /usr/bin/composer /usr/bin/composer

RUN composer config -g github-oauth.github.com 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

RUN chmod 777 /run

RUN a2enmod rewrite

ENV COMPOSER_MEMORY_LIMIT=-1
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
