FROM nginx:1.17.4
RUN apt-get update && apt-get install -y locales locales-all
RUN rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Budapest /etc/localtime
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
