version: '3.1'
services:

    # webservers
    admin-webserver:
        image: nginx:1.17.4
        container_name: project-admin-webserver
        ports:
            - 8081:80
        depends_on:
            - php72
        volumes:
            - './../..:/www/local'
            - ./log:/var/log/nginx
            - ./nginx_backend.conf:/etc/nginx/conf.d/default.conf
        networks:
            - project-network

    frontend-webserver:
        image: nginx:1.17.4
        container_name: project-frontend-webserver
        ports:
            - 8080:80
        depends_on:
            - php72
        volumes:
            - './../..:/www/local'
            - ./log:/var/log/nginx
            - ./nginx_frontend.conf:/etc/nginx/conf.d/default.conf
        networks:
            - project-network

    api-webserver:
        image: nginx:1.17.4
        container_name: project-api-webserver
        ports:
            - 8082:80
        depends_on:
            - php72
        volumes:
            - './../..:/www/local'
            - ./log:/var/log/nginx
            - ./nginx_api.conf:/etc/nginx/conf.d/default.conf
        networks:
            - project-network


    # ez van használatban, 7.4 alatt vannak problémák
    php72:
        build:
            context: .
            dockerfile: dockerfile_php_72
        container_name: project-php72-fpm
        volumes:
            - './../..:/www/local'
            - './php-memory-limit.ini:/usr/local/etc/php/conf.d/php-memory-limit.ini'
        user: ${CURRENT_UID:-}
        working_dir: /www/local
        networks:
            - project-network

    mysql:
        image: mysql:5.6
        container_name: project-db-mysql
        environment:
            MYSQL_ROOT_PASSWORD: project_root_pwd
            MYSQL_DATABASE: project
            MYSQL_USER: test_user
            MYSQL_PASSWORD: asdqwe
        ports:
            - "33062:3306"
        volumes:
            - './../db/project:/var/lib/mysql'
        user: ${CURRENT_UID:-}
        networks:
            - project-network

    mysql82:
        build:
            context: .
            dockerfile: dockerfile_mysql82
        container_name: project-db-mysql
        environment:
            MYSQL_ROOT_PASSWORD: project_root_pwd
            MYSQL_DATABASE: project
            MYSQL_USER: test_user
            MYSQL_PASSWORD: asdqwe
            TZ: Europe/Budapest
            LANG: C.UTF_8
            MYSQL_CHARSET: utf8mb4
            MYSQL_COLLATION: utf8mb4_unicode_ci
        ports:
            - "33063:3306"
        volumes:
            - './../db82/project:/var/lib/mysql'
        user: ${CURRENT_UID:-}
        networks:
            - project-network

    phpmyadmin:
        container_name: 'project-phpmyadmin'
        image: phpmyadmin/phpmyadmin
        ports:
            - "127.0.0.1:43238:80"
        environment:
            - PMA_HOSTS=mysql  #,db
            - UPLOAD_LIMIT=1000M
        networks:
            - project-network

networks:
    project-network:
        driver: bridge
