FROM php:7.2.24-fpm

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update \
    && apt-get install -y \
    wget locales locales-all make git build-essential \
    libmcrypt-dev libwebp-dev libjpeg-dev libpng-dev \
    libfreetype6 libfreetype6-dev xfonts-75dpi xfonts-base \
    libpq-dev libbz2-dev \
    libmagickwand-dev libicu-dev libxml2-dev \
    libzip-dev \
    zip \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install zip

# Install NodeJS
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update && apt-get install -y nodejs && apt-get clean

# Install Php extensions
RUN docker-php-ext-configure gd \
    --with-freetype-dir=/usr/include/ \
    --with-webp-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd

RUN docker-php-ext-install -j$(nproc) \
    pdo pdo_mysql mysqli pgsql \
    bz2 \
    dba \
    intl \
    soap

RUN export MAKEFLAGS="-j $(nproc)" \
  && pecl install imagick-3.4.4 \
  && pecl install mcrypt-1.0.5 \
  && docker-php-ext-enable imagick mcrypt

# Dependency cleanup
RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
RUN rm -f /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Budapest /etc/localtime

# Install Composer
COPY --from=composer:1.10 /usr/bin/composer /usr/bin/composer
RUN composer global require "fxp/composer-asset-plugin:~1.2"
RUN composer config -g github-oauth.github.com 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

RUN chmod 777 /run
RUN locale-gen en_US.UTF-8

RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb
RUN apt install -f -y ./wkhtmltox_0.12.6-1.buster_amd64.deb

ENV COMPOSER_MEMORY_LIMIT=-1
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
